//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcHolderMaster
    {
        public AcHolderMaster()
        {
            this.BankMasters = new HashSet<BankMaster>();
        }
    
        public int AcHolderCode { get; set; }
        public string AcHolderName { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<BankMaster> BankMasters { get; set; }
    }
}
