//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressTypeMaster
    {
        public AddressTypeMaster()
        {
            this.BuyerAddressDetails = new HashSet<BuyerAddressDetail>();
        }
    
        public int AddressTypeId { get; set; }
        public string AddressTypeName { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<BuyerAddressDetail> BuyerAddressDetails { get; set; }
    }
}
