//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvertisementSourceMaster
    {
        public AdvertisementSourceMaster()
        {
            this.ProductLinkMasters = new HashSet<ProductLinkMaster>();
        }
    
        public int SiteId { get; set; }
        public string SiteName { get; set; }
        public string SiteUrl { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<ProductLinkMaster> ProductLinkMasters { get; set; }
    }
}
