//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgencyTypeMaster
    {
        public AgencyTypeMaster()
        {
            this.BuyerMasters = new HashSet<BuyerMaster>();
            this.VendorMasters = new HashSet<VendorMaster>();
        }
    
        public int AgencyTypeId { get; set; }
        public string AgencyType { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<BuyerMaster> BuyerMasters { get; set; }
        public virtual ICollection<VendorMaster> VendorMasters { get; set; }
    }
}
