//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicableChargeMaster
    {
        public ApplicableChargeMaster()
        {
            this.ProductApplicableCharges = new HashSet<ProductApplicableCharge>();
        }
    
        public int ApplicableChargeId { get; set; }
        public string ApplicableChargeName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<ProductApplicableCharge> ProductApplicableCharges { get; set; }
    }
}
