//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetsExpenseMaster
    {
        public int AccountId { get; set; }
        public int LegerId { get; set; }
        public System.DateTime BillDate { get; set; }
        public string BillNo { get; set; }
        public string PartyName { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<decimal> INRAmount { get; set; }
        public string BillPdf { get; set; }
        public string TransactionSlip { get; set; }
        public string Photo { get; set; }
        public string Remark { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> AccountEntryType { get; set; }
        public Nullable<int> TaxId { get; set; }
        public string TaxValue { get; set; }
    
        public virtual CurrencyMaster CurrencyMaster { get; set; }
        public virtual LegerMaster LegerMaster { get; set; }
        public virtual TaxMaster TaxMaster { get; set; }
    }
}
