//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankNameMaster
    {
        public BankNameMaster()
        {
            this.BankMasters = new HashSet<BankMaster>();
            this.BuyerBankDetails = new HashSet<BuyerBankDetail>();
            this.PerformaInvoiceMasters = new HashSet<PerformaInvoiceMaster>();
            this.SupplierBankMasters = new HashSet<SupplierBankMaster>();
            this.UserMasters = new HashSet<UserMaster>();
            this.VendorBankMasters = new HashSet<VendorBankMaster>();
        }
    
        public int BankId { get; set; }
        public string BankName { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<BankMaster> BankMasters { get; set; }
        public virtual ICollection<BuyerBankDetail> BuyerBankDetails { get; set; }
        public virtual ICollection<PerformaInvoiceMaster> PerformaInvoiceMasters { get; set; }
        public virtual ICollection<SupplierBankMaster> SupplierBankMasters { get; set; }
        public virtual ICollection<UserMaster> UserMasters { get; set; }
        public virtual ICollection<VendorBankMaster> VendorBankMasters { get; set; }
    }
}
