//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyerChatDetail
    {
        public int BuyerChatId { get; set; }
        public int BuyerId { get; set; }
        public int ChatId { get; set; }
        public string ChatValue { get; set; }
        public bool IsActive { get; set; }
    
        public virtual BuyerMaster BuyerMaster { get; set; }
        public virtual ChatNameMaster ChatNameMaster { get; set; }
    }
}
