//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyerMaster
    {
        public BuyerMaster()
        {
            this.BuyerAddressDetails = new HashSet<BuyerAddressDetail>();
            this.BuyerBankDetails = new HashSet<BuyerBankDetail>();
            this.BuyerChatDetails = new HashSet<BuyerChatDetail>();
            this.BuyerContactDetails = new HashSet<BuyerContactDetail>();
            this.BuyerLicenseDetails = new HashSet<BuyerLicenseDetail>();
            this.InwardCourierMasters = new HashSet<InwardCourierMaster>();
            this.OutwardCourierMasters = new HashSet<OutwardCourierMaster>();
            this.PerformaInvoiceMasters = new HashSet<PerformaInvoiceMaster>();
            this.ProductCatalogMasters = new HashSet<ProductCatalogMaster>();
            this.ProductPrices = new HashSet<ProductPrice>();
            this.PurchaseOrderMasters = new HashSet<PurchaseOrderMaster>();
            this.SalesOrderMasters = new HashSet<SalesOrderMaster>();
            this.TOMasters = new HashSet<TOMaster>();
        }
    
        public int BuyerId { get; set; }
        public string CompanyName { get; set; }
        public string WebAddress { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsActive { get; set; }
        public string Remark { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string ContactType { get; set; }
        public int AgencyTypeId { get; set; }
        public string Fax { get; set; }
        public string DocumentsData { get; set; }
        public string ConInvId { get; set; }
    
        public virtual AgencyTypeMaster AgencyTypeMaster { get; set; }
        public virtual ICollection<BuyerAddressDetail> BuyerAddressDetails { get; set; }
        public virtual ICollection<BuyerBankDetail> BuyerBankDetails { get; set; }
        public virtual ICollection<BuyerChatDetail> BuyerChatDetails { get; set; }
        public virtual ICollection<BuyerContactDetail> BuyerContactDetails { get; set; }
        public virtual ICollection<BuyerLicenseDetail> BuyerLicenseDetails { get; set; }
        public virtual ICollection<InwardCourierMaster> InwardCourierMasters { get; set; }
        public virtual ICollection<OutwardCourierMaster> OutwardCourierMasters { get; set; }
        public virtual ICollection<PerformaInvoiceMaster> PerformaInvoiceMasters { get; set; }
        public virtual ICollection<ProductCatalogMaster> ProductCatalogMasters { get; set; }
        public virtual ICollection<ProductPrice> ProductPrices { get; set; }
        public virtual ICollection<PurchaseOrderMaster> PurchaseOrderMasters { get; set; }
        public virtual ICollection<SalesOrderMaster> SalesOrderMasters { get; set; }
        public virtual ICollection<TOMaster> TOMasters { get; set; }
    }
}
