//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyerContactDetail
    {
        public BuyerContactDetail()
        {
            this.SalesOrderMasters = new HashSet<SalesOrderMaster>();
        }
    
        public int ContactId { get; set; }
        public int BuyerId { get; set; }
        public string ContactPerson { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public bool IsActive { get; set; }
        public string Surname { get; set; }
        public string ChatDetails { get; set; }
    
        public virtual BuyerMaster BuyerMaster { get; set; }
        public virtual DesignationMaster DesignationMaster { get; set; }
        public virtual ICollection<SalesOrderMaster> SalesOrderMasters { get; set; }
    }
}
