//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatNameMaster
    {
        public ChatNameMaster()
        {
            this.BuyerChatDetails = new HashSet<BuyerChatDetail>();
            this.SupplierChatMasters = new HashSet<SupplierChatMaster>();
            this.VendorChatMasters = new HashSet<VendorChatMaster>();
        }
    
        public int ChatId { get; set; }
        public string ChatName { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<BuyerChatDetail> BuyerChatDetails { get; set; }
        public virtual ICollection<SupplierChatMaster> SupplierChatMasters { get; set; }
        public virtual ICollection<VendorChatMaster> VendorChatMasters { get; set; }
    }
}
