//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityMaster
    {
        public CityMaster()
        {
            this.BuyerAddressDetails = new HashSet<BuyerAddressDetail>();
            this.ExhibitionMasters = new HashSet<ExhibitionMaster>();
            this.InquiryMasters = new HashSet<InquiryMaster>();
            this.InterviweeCandidateMasters = new HashSet<InterviweeCandidateMaster>();
            this.OutwardCourierMasters = new HashSet<OutwardCourierMaster>();
            this.RNDSupplierMasters = new HashSet<RNDSupplierMaster>();
            this.SupplierAddressMasters = new HashSet<SupplierAddressMaster>();
            this.VendorAddressDetails = new HashSet<VendorAddressDetail>();
        }
    
        public int CityId { get; set; }
        public int StateId { get; set; }
        public string CityName { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<BuyerAddressDetail> BuyerAddressDetails { get; set; }
        public virtual StateMaster StateMaster { get; set; }
        public virtual ICollection<ExhibitionMaster> ExhibitionMasters { get; set; }
        public virtual ICollection<InquiryMaster> InquiryMasters { get; set; }
        public virtual ICollection<InterviweeCandidateMaster> InterviweeCandidateMasters { get; set; }
        public virtual ICollection<OutwardCourierMaster> OutwardCourierMasters { get; set; }
        public virtual ICollection<RNDSupplierMaster> RNDSupplierMasters { get; set; }
        public virtual ICollection<SupplierAddressMaster> SupplierAddressMasters { get; set; }
        public virtual ICollection<VendorAddressDetail> VendorAddressDetails { get; set; }
    }
}
