//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyMaster
    {
        public CompanyMaster()
        {
            this.PurchaseOrderMasters = new HashSet<PurchaseOrderMaster>();
            this.QuotationMasters = new HashSet<QuotationMaster>();
            this.SalesOrderMasters = new HashSet<SalesOrderMaster>();
        }
    
        public int ComId { get; set; }
        public string ComCode { get; set; }
        public string ComName { get; set; }
        public string RegOffAdd { get; set; }
        public string CorpOffAdd { get; set; }
        public string TelNos { get; set; }
        public string Email { get; set; }
        public string Web { get; set; }
        public string ComLogo { get; set; }
        public string TaxDetails { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<PurchaseOrderMaster> PurchaseOrderMasters { get; set; }
        public virtual ICollection<QuotationMaster> QuotationMasters { get; set; }
        public virtual ICollection<SalesOrderMaster> SalesOrderMasters { get; set; }
    }
}
