//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactInvitationMaster
    {
        public int ContactInvitationId { get; set; }
        public string ContactInvitation { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
