//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryOfOriginMaster
    {
        public CountryOfOriginMaster()
        {
            this.PerformaProductMasters = new HashSet<PerformaProductMaster>();
            this.SalesItemMasters = new HashSet<SalesItemMaster>();
        }
    
        public int OriginId { get; set; }
        public string CountryOfOrigin { get; set; }
        public bool IsActive { get; set; }
        public int CountryId { get; set; }
    
        public virtual CountryMaster CountryMaster { get; set; }
        public virtual ICollection<PerformaProductMaster> PerformaProductMasters { get; set; }
        public virtual ICollection<SalesItemMaster> SalesItemMasters { get; set; }
    }
}
