//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryMaster
    {
        public CountryMaster()
        {
            this.CountryOfOriginMasters = new HashSet<CountryOfOriginMaster>();
            this.HolidayMasters = new HashSet<HolidayMaster>();
            this.PortMasters = new HashSet<PortMaster>();
            this.StateMasters = new HashSet<StateMaster>();
            this.UserReferenceRelationMasters = new HashSet<UserReferenceRelationMaster>();
        }
    
        public int CountryId { get; set; }
        public string CountryName { get; set; }
        public bool IsActive { get; set; }
        public string CountryCallCode { get; set; }
        public string CountryFlag { get; set; }
        public string CountryAlphaCode { get; set; }
    
        public virtual ICollection<CountryOfOriginMaster> CountryOfOriginMasters { get; set; }
        public virtual ICollection<HolidayMaster> HolidayMasters { get; set; }
        public virtual ICollection<PortMaster> PortMasters { get; set; }
        public virtual ICollection<StateMaster> StateMasters { get; set; }
        public virtual ICollection<UserReferenceRelationMaster> UserReferenceRelationMasters { get; set; }
    }
}
