//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourierTypeMaster
    {
        public CourierTypeMaster()
        {
            this.InwardCourierMasters = new HashSet<InwardCourierMaster>();
            this.OutwardCourierMasters = new HashSet<OutwardCourierMaster>();
        }
    
        public int CourierTypeId { get; set; }
        public string CourierType { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<InwardCourierMaster> InwardCourierMasters { get; set; }
        public virtual ICollection<OutwardCourierMaster> OutwardCourierMasters { get; set; }
    }
}
