//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class elaunch_crmEntities : DbContext
    {
        public elaunch_crmEntities()
            : base("name=elaunch_crmEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
            this.Configuration.ProxyCreationEnabled = false;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccountTypeMaster> AccountTypeMasters { get; set; }
        public DbSet<AcHolderMaster> AcHolderMasters { get; set; }
        public DbSet<AddressTypeMaster> AddressTypeMasters { get; set; }
        public DbSet<AdvertisementSourceMaster> AdvertisementSourceMasters { get; set; }
        public DbSet<AgencyTypeMaster> AgencyTypeMasters { get; set; }
        public DbSet<ApplicableChargeMaster> ApplicableChargeMasters { get; set; }
        public DbSet<AskCustomerDetail> AskCustomerDetails { get; set; }
        public DbSet<AssetsExpenseMaster> AssetsExpenseMasters { get; set; }
        public DbSet<AttendanceMaster> AttendanceMasters { get; set; }
        public DbSet<AutoNumberSetting> AutoNumberSettings { get; set; }
        public DbSet<BankMaster> BankMasters { get; set; }
        public DbSet<BankNameMaster> BankNameMasters { get; set; }
        public DbSet<BillofLoadingMaster> BillofLoadingMasters { get; set; }
        public DbSet<BloodGroupMaster> BloodGroupMasters { get; set; }
        public DbSet<BuyerAddressDetail> BuyerAddressDetails { get; set; }
        public DbSet<BuyerBankDetail> BuyerBankDetails { get; set; }
        public DbSet<BuyerChatDetail> BuyerChatDetails { get; set; }
        public DbSet<BuyerContactDetail> BuyerContactDetails { get; set; }
        public DbSet<BuyerLicenseDetail> BuyerLicenseDetails { get; set; }
        public DbSet<BuyerMaster> BuyerMasters { get; set; }
        public DbSet<CandidateStatusMaster> CandidateStatusMasters { get; set; }
        public DbSet<CategoryMaster> CategoryMasters { get; set; }
        public DbSet<ChatNameMaster> ChatNameMasters { get; set; }
        public DbSet<CityMaster> CityMasters { get; set; }
        public DbSet<CompanyMaster> CompanyMasters { get; set; }
        public DbSet<ContactDocumentNameMaster> ContactDocumentNameMasters { get; set; }
        public DbSet<ContactInvitationMaster> ContactInvitationMasters { get; set; }
        public DbSet<ContactTypeMaster> ContactTypeMasters { get; set; }
        public DbSet<CountryMaster> CountryMasters { get; set; }
        public DbSet<CountryOfOriginMaster> CountryOfOriginMasters { get; set; }
        public DbSet<CourierTypeMaster> CourierTypeMasters { get; set; }
        public DbSet<CurrencyMaster> CurrencyMasters { get; set; }
        public DbSet<DailyWorkReport> DailyWorkReports { get; set; }
        public DbSet<DeliveryTermsMaster> DeliveryTermsMasters { get; set; }
        public DbSet<DepartmentMaster> DepartmentMasters { get; set; }
        public DbSet<DesignationMaster> DesignationMasters { get; set; }
        public DbSet<DocumentNameMaster> DocumentNameMasters { get; set; }
        public DbSet<EmailSpeechMaster> EmailSpeechMasters { get; set; }
        public DbSet<EmpDocumentMaster> EmpDocumentMasters { get; set; }
        public DbSet<EmployeeShitfMaster> EmployeeShitfMasters { get; set; }
        public DbSet<EmpReffTypeMaster> EmpReffTypeMasters { get; set; }
        public DbSet<EventMaster> EventMasters { get; set; }
        public DbSet<EventTypeMaster> EventTypeMasters { get; set; }
        public DbSet<ExhibitionMaster> ExhibitionMasters { get; set; }
        public DbSet<FinancialYearMaster> FinancialYearMasters { get; set; }
        public DbSet<FrequencyMaster> FrequencyMasters { get; set; }
        public DbSet<GroupPermissionMapping> GroupPermissionMappings { get; set; }
        public DbSet<HolidayMaster> HolidayMasters { get; set; }
        public DbSet<HolidayNameMaster> HolidayNameMasters { get; set; }
        public DbSet<InquiryFollowupMaster> InquiryFollowupMasters { get; set; }
        public DbSet<InquiryItemMaster> InquiryItemMasters { get; set; }
        public DbSet<InquiryMaster> InquiryMasters { get; set; }
        public DbSet<IntCanFollowupMaster> IntCanFollowupMasters { get; set; }
        public DbSet<InterviweeCandidateMaster> InterviweeCandidateMasters { get; set; }
        public DbSet<InvoiceTypeMaster> InvoiceTypeMasters { get; set; }
        public DbSet<InwardCourierMaster> InwardCourierMasters { get; set; }
        public DbSet<ITRMaster> ITRMasters { get; set; }
        public DbSet<LeaveMaster> LeaveMasters { get; set; }
        public DbSet<LegerHeadMaster> LegerHeadMasters { get; set; }
        public DbSet<LegerMaster> LegerMasters { get; set; }
        public DbSet<LicenseMaster> LicenseMasters { get; set; }
        public DbSet<LoginHistory> LoginHistories { get; set; }
        public DbSet<MainProductMaster> MainProductMasters { get; set; }
        public DbSet<MenuMaster> MenuMasters { get; set; }
        public DbSet<OutwardCourierMaster> OutwardCourierMasters { get; set; }
        public DbSet<PackingTypeMaster> PackingTypeMasters { get; set; }
        public DbSet<PageOperationMaster> PageOperationMasters { get; set; }
        public DbSet<PaymentModeMaster> PaymentModeMasters { get; set; }
        public DbSet<PaymentTermsMaster> PaymentTermsMasters { get; set; }
        public DbSet<PercentageMaster> PercentageMasters { get; set; }
        public DbSet<PerformaInvoiceMaster> PerformaInvoiceMasters { get; set; }
        public DbSet<PerformaPaymentMaster> PerformaPaymentMasters { get; set; }
        public DbSet<PerformaProductMaster> PerformaProductMasters { get; set; }
        public DbSet<PhaseMaster> PhaseMasters { get; set; }
        public DbSet<PlugShapeMaster> PlugShapeMasters { get; set; }
        public DbSet<PortMaster> PortMasters { get; set; }
        public DbSet<ProductApplicableCharge> ProductApplicableCharges { get; set; }
        public DbSet<ProductCatalogMaster> ProductCatalogMasters { get; set; }
        public DbSet<ProductDocumentMaster> ProductDocumentMasters { get; set; }
        public DbSet<ProductLinkMaster> ProductLinkMasters { get; set; }
        public DbSet<ProductMaster> ProductMasters { get; set; }
        public DbSet<ProductPackingDetail> ProductPackingDetails { get; set; }
        public DbSet<ProductParameterMaster> ProductParameterMasters { get; set; }
        public DbSet<ProductPhotoMaster> ProductPhotoMasters { get; set; }
        public DbSet<ProductPrice> ProductPrices { get; set; }
        public DbSet<ProductSuppDocumentDetail> ProductSuppDocumentDetails { get; set; }
        public DbSet<ProductVideoMaster> ProductVideoMasters { get; set; }
        public DbSet<PurchaseOrderDetailMaster> PurchaseOrderDetailMasters { get; set; }
        public DbSet<PurchaseOrderMaster> PurchaseOrderMasters { get; set; }
        public DbSet<PurchaseOrderTechnicalDetail> PurchaseOrderTechnicalDetails { get; set; }
        public DbSet<QualificationsMaster> QualificationsMasters { get; set; }
        public DbSet<QuotationItemMaster> QuotationItemMasters { get; set; }
        public DbSet<QuotationMaster> QuotationMasters { get; set; }
        public DbSet<ReceiptVoucherMaster> ReceiptVoucherMasters { get; set; }
        public DbSet<ReferenceSourceMaster> ReferenceSourceMasters { get; set; }
        public DbSet<RelationMaster> RelationMasters { get; set; }
        public DbSet<ReligionMaster> ReligionMasters { get; set; }
        public DbSet<ReminderMaster> ReminderMasters { get; set; }
        public DbSet<ReportFormatMaster> ReportFormatMasters { get; set; }
        public DbSet<RNDProductMaster> RNDProductMasters { get; set; }
        public DbSet<RNDSupplierMaster> RNDSupplierMasters { get; set; }
        public DbSet<RoleMaster> RoleMasters { get; set; }
        public DbSet<SalaryHeadMaster> SalaryHeadMasters { get; set; }
        public DbSet<SalesDocumentNameMaster> SalesDocumentNameMasters { get; set; }
        public DbSet<SalesItemMaster> SalesItemMasters { get; set; }
        public DbSet<SalesOrderMaster> SalesOrderMasters { get; set; }
        public DbSet<SalesPurchaseDocumentMaster> SalesPurchaseDocumentMasters { get; set; }
        public DbSet<SalesPurchaseEntryMaster> SalesPurchaseEntryMasters { get; set; }
        public DbSet<SalesTechnicalDetailMaster> SalesTechnicalDetailMasters { get; set; }
        public DbSet<ShapeMaster> ShapeMasters { get; set; }
        public DbSet<ShipmentMarkMaster> ShipmentMarkMasters { get; set; }
        public DbSet<ShipmentMaster> ShipmentMasters { get; set; }
        public DbSet<ShippingOrderMaster> ShippingOrderMasters { get; set; }
        public DbSet<SignatureMaster> SignatureMasters { get; set; }
        public DbSet<SMSSpeechMaster> SMSSpeechMasters { get; set; }
        public DbSet<SourceMaster> SourceMasters { get; set; }
        public DbSet<StateMaster> StateMasters { get; set; }
        public DbSet<SubCategoryMaster> SubCategoryMasters { get; set; }
        public DbSet<SupplierAddressMaster> SupplierAddressMasters { get; set; }
        public DbSet<SupplierBankMaster> SupplierBankMasters { get; set; }
        public DbSet<SupplierChatMaster> SupplierChatMasters { get; set; }
        public DbSet<SupplierContactDetail> SupplierContactDetails { get; set; }
        public DbSet<SupplierLicenseDetail> SupplierLicenseDetails { get; set; }
        public DbSet<SupplierMaster> SupplierMasters { get; set; }
        public DbSet<TaskDetailMaster> TaskDetailMasters { get; set; }
        public DbSet<TaskGroupMaster> TaskGroupMasters { get; set; }
        public DbSet<TaskMaster> TaskMasters { get; set; }
        public DbSet<TaskPriorityMaster> TaskPriorityMasters { get; set; }
        public DbSet<TaskStatusMaster> TaskStatusMasters { get; set; }
        public DbSet<TaskTypeMaster> TaskTypeMasters { get; set; }
        public DbSet<TaxMaster> TaxMasters { get; set; }
        public DbSet<TechnicalSpecHeadMaster> TechnicalSpecHeadMasters { get; set; }
        public DbSet<TechnicalSpecMaster> TechnicalSpecMasters { get; set; }
        public DbSet<TermsAndConditionMaster> TermsAndConditionMasters { get; set; }
        public DbSet<TOItemMaster> TOItemMasters { get; set; }
        public DbSet<TOMaster> TOMasters { get; set; }
        public DbSet<TOTechnicalDetail> TOTechnicalDetails { get; set; }
        public DbSet<TOTypeMaster> TOTypeMasters { get; set; }
        public DbSet<TransactionTypeMaster> TransactionTypeMasters { get; set; }
        public DbSet<TypeOfShipmentMaster> TypeOfShipmentMasters { get; set; }
        public DbSet<UnitConversationMaster> UnitConversationMasters { get; set; }
        public DbSet<UnitMaster> UnitMasters { get; set; }
        public DbSet<UserDocDetail> UserDocDetails { get; set; }
        public DbSet<UserEducationDetail> UserEducationDetails { get; set; }
        public DbSet<UserExperienceDetail> UserExperienceDetails { get; set; }
        public DbSet<UserMaster> UserMasters { get; set; }
        public DbSet<UserReferenceRelationMaster> UserReferenceRelationMasters { get; set; }
        public DbSet<UserRefferenceDetail> UserRefferenceDetails { get; set; }
        public DbSet<UserSalaryDetail> UserSalaryDetails { get; set; }
        public DbSet<VendorAddressDetail> VendorAddressDetails { get; set; }
        public DbSet<VendorBankMaster> VendorBankMasters { get; set; }
        public DbSet<VendorChatMaster> VendorChatMasters { get; set; }
        public DbSet<VendorContactDetail> VendorContactDetails { get; set; }
        public DbSet<VendorLicenseDetail> VendorLicenseDetails { get; set; }
        public DbSet<VendorMaster> VendorMasters { get; set; }
        public DbSet<VoltageMaster> VoltageMasters { get; set; }
        public DbSet<WorkProfileMaster> WorkProfileMasters { get; set; }
        public DbSet<WorkReminderMaster> WorkReminderMasters { get; set; }
    }
}
