//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyMaster
    {
        public CurrencyMaster()
        {
            this.AssetsExpenseMasters = new HashSet<AssetsExpenseMaster>();
            this.OutwardCourierMasters = new HashSet<OutwardCourierMaster>();
            this.PerformaProductMasters = new HashSet<PerformaProductMaster>();
            this.ProductPrices = new HashSet<ProductPrice>();
            this.PurchaseOrderDetailMasters = new HashSet<PurchaseOrderDetailMaster>();
            this.PurchaseOrderMasters = new HashSet<PurchaseOrderMaster>();
            this.RNDSupplierMasters = new HashSet<RNDSupplierMaster>();
            this.SalesItemMasters = new HashSet<SalesItemMaster>();
            this.UserSalaryDetails = new HashSet<UserSalaryDetail>();
        }
    
        public int CurrencyId { get; set; }
        public string CurrencyName { get; set; }
        public bool IsActive { get; set; }
        public string CurrencySymbol { get; set; }
        public string CurrencyCode { get; set; }
    
        public virtual ICollection<AssetsExpenseMaster> AssetsExpenseMasters { get; set; }
        public virtual ICollection<OutwardCourierMaster> OutwardCourierMasters { get; set; }
        public virtual ICollection<PerformaProductMaster> PerformaProductMasters { get; set; }
        public virtual ICollection<ProductPrice> ProductPrices { get; set; }
        public virtual ICollection<PurchaseOrderDetailMaster> PurchaseOrderDetailMasters { get; set; }
        public virtual ICollection<PurchaseOrderMaster> PurchaseOrderMasters { get; set; }
        public virtual ICollection<RNDSupplierMaster> RNDSupplierMasters { get; set; }
        public virtual ICollection<SalesItemMaster> SalesItemMasters { get; set; }
        public virtual ICollection<UserSalaryDetail> UserSalaryDetails { get; set; }
    }
}
