//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyWorkReport
    {
        public int DailyWorkId { get; set; }
        public int UserId { get; set; }
        public System.DateTime Date { get; set; }
        public int TaskInqId { get; set; }
        public int TaskType { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> Persontage { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
    }
}
