//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentMaster
    {
        public DepartmentMaster()
        {
            this.WorkReminderMasters = new HashSet<WorkReminderMaster>();
            this.SignatureMasters = new HashSet<SignatureMaster>();
            this.SMSSpeechMasters = new HashSet<SMSSpeechMaster>();
            this.WorkProfileMasters = new HashSet<WorkProfileMaster>();
        }
    
        public int DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<WorkReminderMaster> WorkReminderMasters { get; set; }
        public virtual ICollection<SignatureMaster> SignatureMasters { get; set; }
        public virtual ICollection<SMSSpeechMaster> SMSSpeechMasters { get; set; }
        public virtual ICollection<WorkProfileMaster> WorkProfileMasters { get; set; }
    }
}
