//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DesignationMaster
    {
        public DesignationMaster()
        {
            this.BuyerContactDetails = new HashSet<BuyerContactDetail>();
            this.UserExperienceDetails = new HashSet<UserExperienceDetail>();
            this.VendorContactDetails = new HashSet<VendorContactDetail>();
        }
    
        public int DesignationId { get; set; }
        public string DesignationName { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<BuyerContactDetail> BuyerContactDetails { get; set; }
        public virtual ICollection<UserExperienceDetail> UserExperienceDetails { get; set; }
        public virtual ICollection<VendorContactDetail> VendorContactDetails { get; set; }
    }
}
