//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentNameMaster
    {
        public DocumentNameMaster()
        {
            this.EmpDocumentMasters = new HashSet<EmpDocumentMaster>();
            this.UserDocDetails = new HashSet<UserDocDetail>();
        }
    
        public int DocId { get; set; }
        public string DocName { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<EmpDocumentMaster> EmpDocumentMasters { get; set; }
        public virtual ICollection<UserDocDetail> UserDocDetails { get; set; }
    }
}
