//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailSpeechMaster
    {
        public EmailSpeechMaster()
        {
            this.RNDProductMasters = new HashSet<RNDProductMaster>();
        }
    
        public int SpeechId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Subject { get; set; }
    
        public virtual ICollection<RNDProductMaster> RNDProductMasters { get; set; }
    }
}
