//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeShitfMaster
    {
        public int ShiftId { get; set; }
        public System.TimeSpan InTime { get; set; }
        public System.TimeSpan OutTime { get; set; }
        public decimal Hours { get; set; }
        public bool IsActive { get; set; }
        public System.TimeSpan LateEntryCalculate { get; set; }
        public string ShiftName { get; set; }
    }
}
