//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExhibitionMaster
    {
        public int ExId { get; set; }
        public string ExName { get; set; }
        public int CityId { get; set; }
        public string Venue { get; set; }
        public string ExProfile { get; set; }
        public string OrganizerDetail { get; set; }
        public string Address { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime ExDate { get; set; }
        public string Tel { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string Web { get; set; }
        public string ContactPerson { get; set; }
        public string Chat { get; set; }
    
        public virtual CityMaster CityMaster { get; set; }
    }
}
