//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupPermissionMapping
    {
        public int PermissionId { get; set; }
        public int GroupId { get; set; }
        public int OperationId { get; set; }
    
        public virtual PageOperationMaster PageOperationMaster { get; set; }
        public virtual RoleMaster RoleMaster { get; set; }
    }
}
