//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HolidayMaster
    {
        public int HolidayId { get; set; }
        public int HolidayNameId { get; set; }
        public int CountryId { get; set; }
        public System.DateTime OnDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsActive { get; set; }
        public string StateIds { get; set; }
        public string ReligionIds { get; set; }
    
        public virtual CountryMaster CountryMaster { get; set; }
        public virtual HolidayNameMaster HolidayNameMaster { get; set; }
    }
}
