//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InquiryItemMaster
    {
        public int InqDetailId { get; set; }
        public int InqId { get; set; }
        public int ProductId { get; set; }
        public string ProductDescription { get; set; }
        public int QtyCode { get; set; }
        public decimal Qty { get; set; }
        public bool IsActive { get; set; }
    
        public virtual InquiryMaster InquiryMaster { get; set; }
        public virtual ProductMaster ProductMaster { get; set; }
        public virtual UnitMaster UnitMaster { get; set; }
    }
}
