//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InquiryFollowupMaster
    {
        public int FollowupId { get; set; }
        public int InqId { get; set; }
        public string CurrentUpdate { get; set; }
        public System.TimeSpan NextFollowTime { get; set; }
        public System.DateTime NextFollowDate { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> Modifydate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public bool IsActive { get; set; }
        public int AssignId { get; set; }
    
        public virtual InquiryMaster InquiryMaster { get; set; }
    }
}
