//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterviweeCandidateMaster
    {
        public InterviweeCandidateMaster()
        {
            this.IntCanFollowupMasters = new HashSet<IntCanFollowupMaster>();
        }
    
        public int IntCandId { get; set; }
        public Nullable<int> ReferenceTypeId { get; set; }
        public Nullable<int> ReferenceId { get; set; }
        public Nullable<int> ReferenceSubType { get; set; }
        public string ReferenceMannualEntry { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Address { get; set; }
        public string Pincode { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public System.DateTime CommunicateDate { get; set; }
        public string FirstName { get; set; }
        public string SurName { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public System.DateTime Birthdate { get; set; }
        public string TotalWorkExperience { get; set; }
        public Nullable<decimal> CurrentCTC { get; set; }
        public Nullable<decimal> CurrentExpected { get; set; }
        public string NoticePeriod { get; set; }
        public string UploadResume { get; set; }
        public Nullable<int> QualificationId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> SourceId { get; set; }
        public string Chat { get; set; }
        public string CandidateRefNo { get; set; }
    
        public virtual CityMaster CityMaster { get; set; }
        public virtual ICollection<IntCanFollowupMaster> IntCanFollowupMasters { get; set; }
        public virtual ReferenceSourceMaster ReferenceSourceMaster { get; set; }
        public virtual QualificationsMaster QualificationsMaster { get; set; }
    }
}
