//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InwardCourierMaster
    {
        public int CourierId { get; set; }
        public System.DateTime CourierDate { get; set; }
        public int SenderId { get; set; }
        public int VendorId { get; set; }
        public string ShipmentRemark { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsActive { get; set; }
        public string SenderType { get; set; }
        public System.TimeSpan CourierTime { get; set; }
        public int ReceivedBy { get; set; }
        public string ShipmentRefNo { get; set; }
        public string POD { get; set; }
        public string VendorName { get; set; }
        public string CourierReffNo { get; set; }
        public Nullable<int> CourierTypeId { get; set; }
        public string ShipmentPhoto { get; set; }
    
        public virtual BuyerMaster BuyerMaster { get; set; }
        public virtual CourierTypeMaster CourierTypeMaster { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
