//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITRMaster
    {
        public ITRMaster()
        {
            this.LegerHeadMasters = new HashSet<LegerHeadMaster>();
        }
    
        public int ITRId { get; set; }
        public string ITRName { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<LegerHeadMaster> LegerHeadMasters { get; set; }
    }
}
