//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveMaster
    {
        public int LeaveId { get; set; }
        public int UserId { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public bool IsHalf { get; set; }
        public decimal TotalDays { get; set; }
        public string Reason { get; set; }
        public int Status { get; set; }
        public string Feedback { get; set; }
        public Nullable<int> FeedbackFrom { get; set; }
        public bool IsActive { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
        public virtual UserMaster UserMaster1 { get; set; }
    }
}
