//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LegerHeadMaster
    {
        public LegerHeadMaster()
        {
            this.LegerMasters = new HashSet<LegerMaster>();
        }
    
        public int LegerHeadId { get; set; }
        public int ITRId { get; set; }
        public string LegerHeadName { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ITRMaster ITRMaster { get; set; }
        public virtual ICollection<LegerMaster> LegerMasters { get; set; }
    }
}
