//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LegerMaster
    {
        public LegerMaster()
        {
            this.AssetsExpenseMasters = new HashSet<AssetsExpenseMaster>();
        }
    
        public int LegerId { get; set; }
        public int LegerHeadId { get; set; }
        public string LegerName { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<AssetsExpenseMaster> AssetsExpenseMasters { get; set; }
        public virtual LegerHeadMaster LegerHeadMaster { get; set; }
    }
}
