//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicenseMaster
    {
        public LicenseMaster()
        {
            this.BuyerLicenseDetails = new HashSet<BuyerLicenseDetail>();
            this.PurchaseOrderMasters = new HashSet<PurchaseOrderMaster>();
            this.SupplierLicenseDetails = new HashSet<SupplierLicenseDetail>();
            this.VendorLicenseDetails = new HashSet<VendorLicenseDetail>();
        }
    
        public int LicenseId { get; set; }
        public string LicenseName { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<BuyerLicenseDetail> BuyerLicenseDetails { get; set; }
        public virtual ICollection<PurchaseOrderMaster> PurchaseOrderMasters { get; set; }
        public virtual ICollection<SupplierLicenseDetail> SupplierLicenseDetails { get; set; }
        public virtual ICollection<VendorLicenseDetail> VendorLicenseDetails { get; set; }
    }
}
