//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutwardCourierMaster
    {
        public int CourierId { get; set; }
        public System.DateTime CourierDate { get; set; }
        public int ReceiverAddressId { get; set; }
        public string ReceiverAddress { get; set; }
        public string ReceiverCity { get; set; }
        public string ReceiverCountry { get; set; }
        public string ReceiverState { get; set; }
        public int VendorId { get; set; }
        public string ShipmentRefNo { get; set; }
        public decimal Amount { get; set; }
        public string PaymentBy { get; set; }
        public string Remark { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> ReceiverId { get; set; }
        public string ReceiverCompanyName { get; set; }
        public string ReceiverType { get; set; }
        public System.TimeSpan CourierTime { get; set; }
        public int SenderBy { get; set; }
        public string POD { get; set; }
        public string ShipmentPhoto { get; set; }
        public string CourierReffNo { get; set; }
        public Nullable<int> CourierTypeId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
    
        public virtual BuyerMaster BuyerMaster { get; set; }
        public virtual CityMaster CityMaster { get; set; }
        public virtual CourierTypeMaster CourierTypeMaster { get; set; }
        public virtual CurrencyMaster CurrencyMaster { get; set; }
    }
}
