//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformaInvoiceMaster
    {
        public PerformaInvoiceMaster()
        {
            this.PerformaProductMasters = new HashSet<PerformaProductMaster>();
            this.PerformaPaymentMasters = new HashSet<PerformaPaymentMaster>();
        }
    
        public int PerformaInvId { get; set; }
        public string PerformaInvNo { get; set; }
        public int RptFormatId { get; set; }
        public System.DateTime PerformaInvDate { get; set; }
        public Nullable<int> DeliveryTermId { get; set; }
        public Nullable<int> PaymentTermId { get; set; }
        public Nullable<int> ModeOfShipmentId { get; set; }
        public Nullable<int> LoadingPortId { get; set; }
        public Nullable<int> DischargePortId { get; set; }
        public string ShippingMarks { get; set; }
        public int ConsigneId { get; set; }
        public string ConsigneName { get; set; }
        public string ConsigneAddress { get; set; }
        public string ConsigneEmail { get; set; }
        public string ConsigneTel { get; set; }
        public string ConsigneTax { get; set; }
        public string ContactName { get; set; }
        public string ContactTel { get; set; }
        public string Contactmail { get; set; }
        public int BankNameId { get; set; }
        public int AccountTypeId { get; set; }
        public string BeneficiaryName { get; set; }
        public string BranchName { get; set; }
        public string BankAddress { get; set; }
        public string AccountNo { get; set; }
        public string IFSCCode { get; set; }
        public string SwiftCode { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual AccountTypeMaster AccountTypeMaster { get; set; }
        public virtual BankNameMaster BankNameMaster { get; set; }
        public virtual BuyerMaster BuyerMaster { get; set; }
        public virtual DeliveryTermsMaster DeliveryTermsMaster { get; set; }
        public virtual PaymentTermsMaster PaymentTermsMaster { get; set; }
        public virtual ICollection<PerformaProductMaster> PerformaProductMasters { get; set; }
        public virtual PortMaster PortMaster { get; set; }
        public virtual ReportFormatMaster ReportFormatMaster { get; set; }
        public virtual ShipmentMaster ShipmentMaster { get; set; }
        public virtual ICollection<PerformaPaymentMaster> PerformaPaymentMasters { get; set; }
    }
}
