//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformaPaymentMaster
    {
        public int PerfomaPaymentId { get; set; }
        public int PerformaInvId { get; set; }
        public System.DateTime DateofReceipt { get; set; }
        public decimal ReceivedAmount { get; set; }
        public int PaymentModeId { get; set; }
        public int TransactionTypeId { get; set; }
        public string ReceivedRemark { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual PaymentModeMaster PaymentModeMaster { get; set; }
        public virtual PerformaInvoiceMaster PerformaInvoiceMaster { get; set; }
        public virtual TransactionTypeMaster TransactionTypeMaster { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
