//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhaseMaster
    {
        public PhaseMaster()
        {
            this.ProductPackingDetails = new HashSet<ProductPackingDetail>();
        }
    
        public int PhaseId { get; set; }
        public string Phase { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<ProductPackingDetail> ProductPackingDetails { get; set; }
    }
}
