//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortMaster
    {
        public PortMaster()
        {
            this.PerformaInvoiceMasters = new HashSet<PerformaInvoiceMaster>();
            this.PurchaseOrderMasters = new HashSet<PurchaseOrderMaster>();
            this.QuotationMasters = new HashSet<QuotationMaster>();
            this.ShipmentMarkMasters = new HashSet<ShipmentMarkMaster>();
            this.ShipmentMarkMasters1 = new HashSet<ShipmentMarkMaster>();
        }
    
        public int PortId { get; set; }
        public string PortName { get; set; }
        public bool IsActive { get; set; }
        public int CountryId { get; set; }
    
        public virtual CountryMaster CountryMaster { get; set; }
        public virtual ICollection<PerformaInvoiceMaster> PerformaInvoiceMasters { get; set; }
        public virtual ICollection<PurchaseOrderMaster> PurchaseOrderMasters { get; set; }
        public virtual ICollection<QuotationMaster> QuotationMasters { get; set; }
        public virtual ICollection<ShipmentMarkMaster> ShipmentMarkMasters { get; set; }
        public virtual ICollection<ShipmentMarkMaster> ShipmentMarkMasters1 { get; set; }
    }
}
