//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSuppDocumentDetail
    {
        public int PrdSupDocId { get; set; }
        public int ProductId { get; set; }
        public int CatalogId { get; set; }
        public int PrdDocId { get; set; }
        public string DocPath { get; set; }
        public string Remark { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsActive { get; set; }
    }
}
