//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCatalogMaster
    {
        public ProductCatalogMaster()
        {
            this.ProductLinkMasters = new HashSet<ProductLinkMaster>();
            this.ProductParameterMasters = new HashSet<ProductParameterMaster>();
            this.ProductPackingDetails = new HashSet<ProductPackingDetail>();
            this.ProductPhotoMasters = new HashSet<ProductPhotoMaster>();
            this.ProductVideoMasters = new HashSet<ProductVideoMaster>();
        }
    
        public int CatalogId { get; set; }
        public int ProductId { get; set; }
        public string CatalogPath { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string SupplierModelNo { get; set; }
        public string ProductModelNo { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CountryOfOriginId { get; set; }
        public string Capacity { get; set; }
    
        public virtual BuyerMaster BuyerMaster { get; set; }
        public virtual ICollection<ProductLinkMaster> ProductLinkMasters { get; set; }
        public virtual ICollection<ProductParameterMaster> ProductParameterMasters { get; set; }
        public virtual ICollection<ProductPackingDetail> ProductPackingDetails { get; set; }
        public virtual ICollection<ProductPhotoMaster> ProductPhotoMasters { get; set; }
        public virtual ICollection<ProductVideoMaster> ProductVideoMasters { get; set; }
        public virtual ProductMaster ProductMaster { get; set; }
    }
}
