//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPrice
    {
        public ProductPrice()
        {
            this.ProductApplicableCharges = new HashSet<ProductApplicableCharge>();
            this.QuotationItemMasters = new HashSet<QuotationItemMaster>();
        }
    
        public int ProductPriceId { get; set; }
        public int ProductId { get; set; }
        public int CurrencyId { get; set; }
        public decimal BaseAmount { get; set; }
        public decimal TotalCharge { get; set; }
        public decimal TotalAmount { get; set; }
        public int SupplierId { get; set; }
    
        public virtual BuyerMaster BuyerMaster { get; set; }
        public virtual CurrencyMaster CurrencyMaster { get; set; }
        public virtual ICollection<ProductApplicableCharge> ProductApplicableCharges { get; set; }
        public virtual ProductMaster ProductMaster { get; set; }
        public virtual ICollection<QuotationItemMaster> QuotationItemMasters { get; set; }
    }
}
