//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductVideoMaster
    {
        public int VideoId { get; set; }
        public int ProductId { get; set; }
        public string URL { get; set; }
        public bool IsDefault { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CatalogId { get; set; }
    
        public virtual ProductCatalogMaster ProductCatalogMaster { get; set; }
        public virtual ProductMaster ProductMaster { get; set; }
    }
}
