//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductApplicableCharge
    {
        public int ApplicableId { get; set; }
        public int ProductPriceId { get; set; }
        public int AppChargeId { get; set; }
        public string AppCharge { get; set; }
        public Nullable<double> Percentage { get; set; }
        public Nullable<double> Amount { get; set; }
        public double ApplicableAmount { get; set; }
    
        public virtual ApplicableChargeMaster ApplicableChargeMaster { get; set; }
        public virtual ProductPrice ProductPrice { get; set; }
    }
}
