//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMaster
    {
        public ProductMaster()
        {
            this.InquiryItemMasters = new HashSet<InquiryItemMaster>();
            this.PerformaProductMasters = new HashSet<PerformaProductMaster>();
            this.ProductCatalogMasters = new HashSet<ProductCatalogMaster>();
            this.ProductLinkMasters = new HashSet<ProductLinkMaster>();
            this.ProductPackingDetails = new HashSet<ProductPackingDetail>();
            this.ProductParameterMasters = new HashSet<ProductParameterMaster>();
            this.ProductPhotoMasters = new HashSet<ProductPhotoMaster>();
            this.ProductPrices = new HashSet<ProductPrice>();
            this.ProductVideoMasters = new HashSet<ProductVideoMaster>();
            this.PurchaseOrderDetailMasters = new HashSet<PurchaseOrderDetailMaster>();
            this.QuotationItemMasters = new HashSet<QuotationItemMaster>();
            this.SalesItemMasters = new HashSet<SalesItemMaster>();
            this.TOItemMasters = new HashSet<TOItemMaster>();
        }
    
        public int ProductId { get; set; }
        public int SubCategoryId { get; set; }
        public string ProductName { get; set; }
        public string HSCode { get; set; }
        public string ProductCode { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsActive { get; set; }
        public string Keywords { get; set; }
        public string GPlusLink { get; set; }
        public string FbLink { get; set; }
        public string GDriveLink { get; set; }
        public string DropboxLink { get; set; }
        public string Functionality { get; set; }
        public string SupplierCatalogimg { get; set; }
        public string OurCatalogImg { get; set; }
    
        public virtual ICollection<InquiryItemMaster> InquiryItemMasters { get; set; }
        public virtual ICollection<PerformaProductMaster> PerformaProductMasters { get; set; }
        public virtual ICollection<ProductCatalogMaster> ProductCatalogMasters { get; set; }
        public virtual ICollection<ProductLinkMaster> ProductLinkMasters { get; set; }
        public virtual ICollection<ProductPackingDetail> ProductPackingDetails { get; set; }
        public virtual SubCategoryMaster SubCategoryMaster { get; set; }
        public virtual ICollection<ProductParameterMaster> ProductParameterMasters { get; set; }
        public virtual ICollection<ProductPhotoMaster> ProductPhotoMasters { get; set; }
        public virtual ICollection<ProductPrice> ProductPrices { get; set; }
        public virtual ICollection<ProductVideoMaster> ProductVideoMasters { get; set; }
        public virtual ICollection<PurchaseOrderDetailMaster> PurchaseOrderDetailMasters { get; set; }
        public virtual ICollection<QuotationItemMaster> QuotationItemMasters { get; set; }
        public virtual ICollection<SalesItemMaster> SalesItemMasters { get; set; }
        public virtual ICollection<TOItemMaster> TOItemMasters { get; set; }
    }
}
