//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderDetailMaster
    {
        public PurchaseOrderDetailMaster()
        {
            this.PurchaseOrderTechnicalDetails = new HashSet<PurchaseOrderTechnicalDetail>();
        }
    
        public int PoDetailId { get; set; }
        public int PoId { get; set; }
        public int ProductId { get; set; }
        public string Description { get; set; }
        public int QtyCode { get; set; }
        public decimal Qty { get; set; }
        public int PriceCode { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Amount { get; set; }
        public bool IsActive { get; set; }
        public string ModelNo { get; set; }
        public string ProductPhotoes { get; set; }
        public string MachinaryPhotoes { get; set; }
    
        public virtual CurrencyMaster CurrencyMaster { get; set; }
        public virtual ProductMaster ProductMaster { get; set; }
        public virtual PurchaseOrderMaster PurchaseOrderMaster { get; set; }
        public virtual UnitMaster UnitMaster { get; set; }
        public virtual ICollection<PurchaseOrderTechnicalDetail> PurchaseOrderTechnicalDetails { get; set; }
    }
}
