//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderTechnicalDetail
    {
        public int POSpecId { get; set; }
        public int SpecId { get; set; }
        public string SpecVal { get; set; }
        public int PoDetailId { get; set; }
    
        public virtual PurchaseOrderDetailMaster PurchaseOrderDetailMaster { get; set; }
        public virtual TechnicalSpecMaster TechnicalSpecMaster { get; set; }
    }
}
