//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenceSourceMaster
    {
        public ReferenceSourceMaster()
        {
            this.InterviweeCandidateMasters = new HashSet<InterviweeCandidateMaster>();
        }
    
        public int SourceId { get; set; }
        public string SourceName { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<InterviweeCandidateMaster> InterviweeCandidateMasters { get; set; }
    }
}
