//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelationMaster
    {
        public RelationMaster()
        {
            this.UserReferenceRelationMasters = new HashSet<UserReferenceRelationMaster>();
        }
    
        public int RelationId { get; set; }
        public string RelationName { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<UserReferenceRelationMaster> UserReferenceRelationMasters { get; set; }
    }
}
