//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReminderMaster
    {
        public int ReminderId { get; set; }
        public string ReminderName { get; set; }
        public System.DateTime ReminderDate { get; set; }
        public string Cycle { get; set; }
        public string Remark { get; set; }
        public bool IsActive { get; set; }
    }
}
