//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RNDSupplierMaster
    {
        public int RNDSupplierId { get; set; }
        public int RNDProductId { get; set; }
        public string CompanyName { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Attende { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Remark { get; set; }
        public string Quotations { get; set; }
        public int CityId { get; set; }
        public string Website { get; set; }
        public string TeliPhoneNo { get; set; }
        public Nullable<int> UnitId { get; set; }
        public string Catalogue { get; set; }
        public string CommunicationRecord { get; set; }
        public string Chat { get; set; }
        public string ContactEmail { get; set; }
        public string Pincode { get; set; }
    
        public virtual CityMaster CityMaster { get; set; }
        public virtual CurrencyMaster CurrencyMaster { get; set; }
        public virtual RNDProductMaster RNDProductMaster { get; set; }
    }
}
