//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderMaster
    {
        public SalesOrderMaster()
        {
            this.SalesItemMasters = new HashSet<SalesItemMaster>();
        }
    
        public int SOId { get; set; }
        public string SoNo { get; set; }
        public System.DateTime SoDate { get; set; }
        public int BuyerId { get; set; }
        public int BuyerContactId { get; set; }
        public string Remark { get; set; }
        public decimal TotalAmount { get; set; }
        public int TotalAmountCode { get; set; }
        public int DeliveryTermId { get; set; }
        public int PaymentTermId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsActive { get; set; }
        public string SoRefNo { get; set; }
        public int CompanyId { get; set; }
    
        public virtual BuyerContactDetail BuyerContactDetail { get; set; }
        public virtual BuyerMaster BuyerMaster { get; set; }
        public virtual CompanyMaster CompanyMaster { get; set; }
        public virtual DeliveryTermsMaster DeliveryTermsMaster { get; set; }
        public virtual PaymentTermsMaster PaymentTermsMaster { get; set; }
        public virtual ICollection<SalesItemMaster> SalesItemMasters { get; set; }
    }
}
