//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesPurchaseDocumentMaster
    {
        public int SalesPurchaseDocId { get; set; }
        public int SalesPurchaseId { get; set; }
        public int DocId { get; set; }
        public string DocPath { get; set; }
    
        public virtual SalesDocumentNameMaster SalesDocumentNameMaster { get; set; }
        public virtual SalesPurchaseEntryMaster SalesPurchaseEntryMaster { get; set; }
    }
}
