//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentMaster
    {
        public ShipmentMaster()
        {
            this.PerformaInvoiceMasters = new HashSet<PerformaInvoiceMaster>();
            this.PurchaseOrderMasters = new HashSet<PurchaseOrderMaster>();
            this.PurchaseOrderMasters1 = new HashSet<PurchaseOrderMaster>();
        }
    
        public int ShipmentId { get; set; }
        public string ModeOfShipment { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<PerformaInvoiceMaster> PerformaInvoiceMasters { get; set; }
        public virtual ICollection<PurchaseOrderMaster> PurchaseOrderMasters { get; set; }
        public virtual ICollection<PurchaseOrderMaster> PurchaseOrderMasters1 { get; set; }
    }
}
