//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentMarkMaster
    {
        public int ShipmentMarkId { get; set; }
        public string BuyerName { get; set; }
        public string ShipperName { get; set; }
        public string ConsigneeName { get; set; }
        public int POL { get; set; }
        public int POD { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual PortMaster PortMaster { get; set; }
        public virtual PortMaster PortMaster1 { get; set; }
    }
}
