//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingOrderMaster
    {
        public int ShippingOrdId { get; set; }
        public string TypeofShipment { get; set; }
        public string Commodity { get; set; }
        public string Nooftotal { get; set; }
        public string NoofBL { get; set; }
        public string CPBuyerName { get; set; }
        public string CPBuyerAddress { get; set; }
        public string CPBuyerTelephone { get; set; }
        public string CPBuyerFax { get; set; }
        public string CPBuyerContactPerson { get; set; }
        public string EDBuyerName { get; set; }
        public string EDBuyerAddress { get; set; }
        public string EDBuyerTelephone { get; set; }
        public string EDBuyerContactPerson { get; set; }
        public string Freight { get; set; }
        public string POL { get; set; }
        public string POD { get; set; }
        public string ProductDescription { get; set; }
        public string ShippingMarksNumber { get; set; }
        public string TotalNOPkgs { get; set; }
        public Nullable<decimal> TotalGross { get; set; }
        public Nullable<decimal> Measurement { get; set; }
        public string Shipmentterms { get; set; }
        public string CompanyName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
