//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSSpeechMaster
    {
        public SMSSpeechMaster()
        {
            this.RNDProductMasters = new HashSet<RNDProductMaster>();
        }
    
        public int SMSId { get; set; }
        public string SMSTitle { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string SMS { get; set; }
        public bool IsActive { get; set; }
    
        public virtual DepartmentMaster DepartmentMaster { get; set; }
        public virtual ICollection<RNDProductMaster> RNDProductMasters { get; set; }
    }
}
