//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierLicenseDetail
    {
        public int SupplierLicenseId { get; set; }
        public int SupplierId { get; set; }
        public int LicenseId { get; set; }
        public string LicenseNo { get; set; }
    
        public virtual LicenseMaster LicenseMaster { get; set; }
        public virtual SupplierMaster SupplierMaster { get; set; }
    }
}
