//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierMaster
    {
        public SupplierMaster()
        {
            this.SupplierAddressMasters = new HashSet<SupplierAddressMaster>();
            this.SupplierBankMasters = new HashSet<SupplierBankMaster>();
            this.SupplierChatMasters = new HashSet<SupplierChatMaster>();
            this.SupplierContactDetails = new HashSet<SupplierContactDetail>();
            this.SupplierLicenseDetails = new HashSet<SupplierLicenseDetail>();
        }
    
        public int SupplierId { get; set; }
        public string CompanyName { get; set; }
        public string Website { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsActive { get; set; }
        public string CompanyEmail { get; set; }
        public string Remark { get; set; }
    
        public virtual ICollection<SupplierAddressMaster> SupplierAddressMasters { get; set; }
        public virtual ICollection<SupplierBankMaster> SupplierBankMasters { get; set; }
        public virtual ICollection<SupplierChatMaster> SupplierChatMasters { get; set; }
        public virtual ICollection<SupplierContactDetail> SupplierContactDetails { get; set; }
        public virtual ICollection<SupplierLicenseDetail> SupplierLicenseDetails { get; set; }
    }
}
