//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskMaster
    {
        public TaskMaster()
        {
            this.TaskDetailMasters = new HashSet<TaskDetailMaster>();
        }
    
        public int TaskId { get; set; }
        public string Task { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Review { get; set; }
        public int Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> TaskTypeId { get; set; }
        public string GroupBy { get; set; }
        public Nullable<int> TaskGroupId { get; set; }
        public string TaskNo { get; set; }
        public Nullable<System.DateTime> DeadlineDate { get; set; }
        public string Duration { get; set; }
    
        public virtual ICollection<TaskDetailMaster> TaskDetailMasters { get; set; }
        public virtual TaskGroupMaster TaskGroupMaster { get; set; }
        public virtual TaskTypeMaster TaskTypeMaster { get; set; }
    }
}
