//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskDetailMaster
    {
        public int TaskDetailId { get; set; }
        public int TaskId { get; set; }
        public Nullable<int> FromId { get; set; }
        public Nullable<int> ToId { get; set; }
        public Nullable<System.DateTime> NextFollowDate { get; set; }
        public Nullable<System.TimeSpan> NextFollowTime { get; set; }
        public bool IsActive { get; set; }
        public string Note { get; set; }
        public Nullable<int> TaskStatus { get; set; }
        public Nullable<System.DateTime> PlanDateTime { get; set; }
        public Nullable<System.DateTime> ActualDate { get; set; }
        public Nullable<System.TimeSpan> ActualTime { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual TaskMaster TaskMaster { get; set; }
        public virtual TaskStatusMaster TaskStatusMaster { get; set; }
    }
}
