//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskGroupMaster
    {
        public TaskGroupMaster()
        {
            this.TaskMasters = new HashSet<TaskMaster>();
        }
    
        public int TaskGroupId { get; set; }
        public string TaskGroupName { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<TaskMaster> TaskMasters { get; set; }
    }
}
