//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxMaster
    {
        public TaxMaster()
        {
            this.AssetsExpenseMasters = new HashSet<AssetsExpenseMaster>();
        }
    
        public int TaxId { get; set; }
        public string TaxName { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<AssetsExpenseMaster> AssetsExpenseMasters { get; set; }
    }
}
