//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOItemMaster
    {
        public TOItemMaster()
        {
            this.TOTechnicalDetails = new HashSet<TOTechnicalDetail>();
        }
    
        public int TOItemId { get; set; }
        public int TOId { get; set; }
        public int ProductId { get; set; }
    
        public virtual ProductMaster ProductMaster { get; set; }
        public virtual TOMaster TOMaster { get; set; }
        public virtual ICollection<TOTechnicalDetail> TOTechnicalDetails { get; set; }
    }
}
