//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOMaster
    {
        public TOMaster()
        {
            this.TOItemMasters = new HashSet<TOItemMaster>();
            this.TOTechnicalDetails = new HashSet<TOTechnicalDetail>();
        }
    
        public int TOId { get; set; }
        public int InqId { get; set; }
        public Nullable<int> BuyerId { get; set; }
        public Nullable<int> ToTypeId { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string Remark { get; set; }
    
        public virtual BuyerMaster BuyerMaster { get; set; }
        public virtual InquiryMaster InquiryMaster { get; set; }
        public virtual ICollection<TOItemMaster> TOItemMasters { get; set; }
        public virtual TOTypeMaster TOTypeMaster { get; set; }
        public virtual ICollection<TOTechnicalDetail> TOTechnicalDetails { get; set; }
    }
}
