//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOTechnicalDetail
    {
        public int TechDetailId { get; set; }
        public int TOId { get; set; }
        public int TOItemId { get; set; }
        public int ProductId { get; set; }
        public int TechParaID { get; set; }
        public string TechParaVal { get; set; }
        public string TechParaRequirment { get; set; }
        public int TechSpecifType { get; set; }
    
        public virtual TechnicalSpecMaster TechnicalSpecMaster { get; set; }
        public virtual TOItemMaster TOItemMaster { get; set; }
        public virtual TOMaster TOMaster { get; set; }
    }
}
