//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitMaster
    {
        public UnitMaster()
        {
            this.InquiryItemMasters = new HashSet<InquiryItemMaster>();
            this.PerformaProductMasters = new HashSet<PerformaProductMaster>();
            this.PurchaseOrderDetailMasters = new HashSet<PurchaseOrderDetailMaster>();
            this.QuotationItemMasters = new HashSet<QuotationItemMaster>();
            this.SalesItemMasters = new HashSet<SalesItemMaster>();
        }
    
        public int UnitId { get; set; }
        public string UnitName { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<InquiryItemMaster> InquiryItemMasters { get; set; }
        public virtual ICollection<PerformaProductMaster> PerformaProductMasters { get; set; }
        public virtual ICollection<PurchaseOrderDetailMaster> PurchaseOrderDetailMasters { get; set; }
        public virtual ICollection<QuotationItemMaster> QuotationItemMasters { get; set; }
        public virtual ICollection<SalesItemMaster> SalesItemMasters { get; set; }
    }
}
