//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitConversationMaster
    {
        public int ID { get; set; }
        public string FromUnit { get; set; }
        public string ToUnit { get; set; }
        public decimal Ratio { get; set; }
        public bool IsActive { get; set; }
    }
}
