//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserExperienceDetail
    {
        public int EduId { get; set; }
        public int UserId { get; set; }
        public string OrganizationName { get; set; }
        public Nullable<int> CityId { get; set; }
        public string PinCode { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string TotalWorkExperience { get; set; }
        public Nullable<int> Designation { get; set; }
        public string Description { get; set; }
    
        public virtual DesignationMaster DesignationMaster { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
