//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSalaryDetail
    {
        public int EmpSalId { get; set; }
        public int UserId { get; set; }
        public int SalaryHeadId { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<decimal> INRAmount { get; set; }
    
        public virtual CurrencyMaster CurrencyMaster { get; set; }
        public virtual SalaryHeadMaster SalaryHeadMaster { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
