//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDocDetail
    {
        public int EmpDocId { get; set; }
        public int UserId { get; set; }
        public int DocId { get; set; }
        public string DocValue { get; set; }
        public string DocUpload { get; set; }
    
        public virtual DocumentNameMaster DocumentNameMaster { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
