//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        public UserMaster()
        {
            this.AttendanceMasters = new HashSet<AttendanceMaster>();
            this.DailyWorkReports = new HashSet<DailyWorkReport>();
            this.EmpDocumentMasters = new HashSet<EmpDocumentMaster>();
            this.InwardCourierMasters = new HashSet<InwardCourierMaster>();
            this.LeaveMasters = new HashSet<LeaveMaster>();
            this.LeaveMasters1 = new HashSet<LeaveMaster>();
            this.PerformaPaymentMasters = new HashSet<PerformaPaymentMaster>();
            this.UserDocDetails = new HashSet<UserDocDetail>();
            this.UserEducationDetails = new HashSet<UserEducationDetail>();
            this.UserExperienceDetails = new HashSet<UserExperienceDetail>();
            this.UserReferenceRelationMasters = new HashSet<UserReferenceRelationMaster>();
            this.UserRefferenceDetails = new HashSet<UserRefferenceDetail>();
            this.UserSalaryDetails = new HashSet<UserSalaryDetail>();
        }
    
        public int UserId { get; set; }
        public string UserCode { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public string Surname { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public Nullable<int> BirthPlaceCityId { get; set; }
        public string BirthPlaceArea { get; set; }
        public string BirthPlacePincode { get; set; }
        public Nullable<int> HomeTownCityId { get; set; }
        public string HomeTownArea { get; set; }
        public string HomeTownPincode { get; set; }
        public Nullable<int> BloodGroupId { get; set; }
        public string Email { get; set; }
        public string MobNo { get; set; }
        public string ResidentNo { get; set; }
        public string PresentArea { get; set; }
        public Nullable<int> PresentCityId { get; set; }
        public string PresentPinCode { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentArea { get; set; }
        public Nullable<int> PermanentCityId { get; set; }
        public string PermanentPinCode { get; set; }
        public string PermanentAddress { get; set; }
        public string DrivingLicNo { get; set; }
        public string VoterIdNumber { get; set; }
        public string PassportNo { get; set; }
        public string PANNo { get; set; }
        public string AadharNo { get; set; }
        public string FullNameAsPerBank { get; set; }
        public string BranchName { get; set; }
        public Nullable<int> BankName { get; set; }
        public string AccountNo { get; set; }
        public Nullable<int> AccountTypeId { get; set; }
        public string IFSC { get; set; }
        public Nullable<int> ReportingId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> ReferenceTypeId { get; set; }
        public Nullable<int> ReferenceSubType { get; set; }
        public Nullable<int> ReferenceId { get; set; }
        public string ReferenceMannualEntry { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> PresentPropType { get; set; }
        public Nullable<int> PermanentPropType { get; set; }
        public string MICRCode { get; set; }
        public string Photo { get; set; }
        public string ChatDetail { get; set; }
        public Nullable<System.TimeSpan> ShiftStartTime { get; set; }
        public Nullable<System.TimeSpan> ShiftEndTime { get; set; }
        public Nullable<System.TimeSpan> LunchStartTime { get; set; }
        public Nullable<System.TimeSpan> LunchEndTime { get; set; }
        public Nullable<System.DateTime> CommunicationDate { get; set; }
        public string ContactMobile { get; set; }
        public string ContactEmail { get; set; }
        public string ContactChat { get; set; }
        public Nullable<int> SourceId { get; set; }
    
        public virtual ICollection<AttendanceMaster> AttendanceMasters { get; set; }
        public virtual BankNameMaster BankNameMaster { get; set; }
        public virtual ICollection<DailyWorkReport> DailyWorkReports { get; set; }
        public virtual ICollection<EmpDocumentMaster> EmpDocumentMasters { get; set; }
        public virtual ICollection<InwardCourierMaster> InwardCourierMasters { get; set; }
        public virtual ICollection<LeaveMaster> LeaveMasters { get; set; }
        public virtual ICollection<LeaveMaster> LeaveMasters1 { get; set; }
        public virtual ICollection<PerformaPaymentMaster> PerformaPaymentMasters { get; set; }
        public virtual RoleMaster RoleMaster { get; set; }
        public virtual SourceMaster SourceMaster { get; set; }
        public virtual ICollection<UserDocDetail> UserDocDetails { get; set; }
        public virtual ICollection<UserEducationDetail> UserEducationDetails { get; set; }
        public virtual ICollection<UserExperienceDetail> UserExperienceDetails { get; set; }
        public virtual UserMaster UserMaster1 { get; set; }
        public virtual UserMaster UserMaster2 { get; set; }
        public virtual ICollection<UserReferenceRelationMaster> UserReferenceRelationMasters { get; set; }
        public virtual ICollection<UserRefferenceDetail> UserRefferenceDetails { get; set; }
        public virtual ICollection<UserSalaryDetail> UserSalaryDetails { get; set; }
    }
}
