//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRefferenceDetail
    {
        public int ReffId { get; set; }
        public int UserId { get; set; }
        public int ReffType { get; set; }
        public string ReffName { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public int CityId { get; set; }
        public string Pincode { get; set; }
    
        public virtual EmpReffTypeMaster EmpReffTypeMaster { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
