//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorContactDetail
    {
        public int ContactId { get; set; }
        public int VendorId { get; set; }
        public string ContactName { get; set; }
        public string MobileNo { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public string Email { get; set; }
        public bool IsActive { get; set; }
        public string Surname { get; set; }
    
        public virtual DesignationMaster DesignationMaster { get; set; }
        public virtual VendorMaster VendorMaster { get; set; }
    }
}
