//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorBankMaster
    {
        public int BankDetailId { get; set; }
        public int VendorId { get; set; }
        public int BankNameId { get; set; }
        public string IFSCCode { get; set; }
        public string AccountNo { get; set; }
        public string BeneficiaryName { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsActive { get; set; }
        public string BranchName { get; set; }
        public int AccountTypeId { get; set; }
        public string SwiftCode { get; set; }
        public string NickName { get; set; }
    
        public virtual AccountTypeMaster AccountTypeMaster { get; set; }
        public virtual BankNameMaster BankNameMaster { get; set; }
        public virtual VendorMaster VendorMaster { get; set; }
    }
}
