//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorMaster
    {
        public VendorMaster()
        {
            this.VendorAddressDetails = new HashSet<VendorAddressDetail>();
            this.VendorBankMasters = new HashSet<VendorBankMaster>();
            this.VendorChatMasters = new HashSet<VendorChatMaster>();
            this.VendorContactDetails = new HashSet<VendorContactDetail>();
            this.VendorLicenseDetails = new HashSet<VendorLicenseDetail>();
        }
    
        public int VendorId { get; set; }
        public int AgencyTypeId { get; set; }
        public string CompanyName { get; set; }
        public string Website { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsActive { get; set; }
        public string Remark { get; set; }
        public string CompanyEmail { get; set; }
    
        public virtual AgencyTypeMaster AgencyTypeMaster { get; set; }
        public virtual ICollection<VendorAddressDetail> VendorAddressDetails { get; set; }
        public virtual ICollection<VendorBankMaster> VendorBankMasters { get; set; }
        public virtual ICollection<VendorChatMaster> VendorChatMasters { get; set; }
        public virtual ICollection<VendorContactDetail> VendorContactDetails { get; set; }
        public virtual ICollection<VendorLicenseDetail> VendorLicenseDetails { get; set; }
    }
}
