//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorLicenseDetail
    {
        public int VendorLicenseId { get; set; }
        public int VendorId { get; set; }
        public int LicenseId { get; set; }
        public string LicenseNo { get; set; }
    
        public virtual LicenseMaster LicenseMaster { get; set; }
        public virtual VendorMaster VendorMaster { get; set; }
    }
}
